baseURL                   = "https://www.pott.dev"
builddrafts                = false
languageCode               = "en-US"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "../"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

theme                      = "Everything"
title                      = "pott.dev"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"  

  [[menu.main]]
    name                   = "About"
    weight                 = -0
    identifier             = "about"
    url                    = "about/"  

 

[params]
  faviconfile              = "img/logo.png"               # from static/
  avatar                   = "img/profile.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Johannes"
  description              = ["Software Developer", "Freethinker", "Music Enthusiast"]           # appears in the site header when set to a non-empty string
  welcome_head             = "Welcome to pott.dev!"
  welcome_word             = "Find blog posts, software projects and more"

  latestpostscount         = 4                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "2 Jan, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/Everything/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "johannes.ptaszyk@pott.dev"
  github                   = "//github.com/johannesptaszyk"
  twitter                  = "//twitter.com/jptaszyk" 
  include_rss              = false                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = ""
    
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
